---
- hosts: db
  remote_user: ubuntu
  become: yes
  gather_facts: False
  vars_files:
    - ./token.yml

  pre_tasks:

    - name: 'install python'
      raw: 'sudo apt-get -y install python'

    - name: 'install pip'
      raw: 'sudo apt-get update && sudo apt-get install python-pip -y'

    - name: 'Install docker-py module'
      raw: 'sudo pip install docker-py'

  tasks:

    - name: "APT - Add Docker GPG key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "APT - Add Docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
        filename: docker

    - name: "APT - install misc packages"
      apt:
        name: ['aptitude', 'apt-transport-https', 'ca-certificates', 'curl','software-properties-common']
        update_cache: yes

    - name: "APT - install 'docker-ce'"
      apt:
        name: "docker-ce"
        update_cache: yes

    - name: pull mySQL docker image from docker hub
      docker_image:
        name: mysql:5.6

    - name: Copy env files
      copy:
        src: ./app.env
        dest: /home/ubuntu/app/
        mode: 0644

    - name: Join docker swarm as worker node
      docker_swarm:
        state: join
        advertise_addr: 192.168.10.120
        join_token: "{{ WORKER_TOKEN }}"
        remote_addrs: [ '192.168.10.100:2377' ]

    #Anisble module not able to find overlay network
    # - name: Running the container
    #   docker_container:
    #     name: snipe-mysql
    #     env_file: /home/ubuntu/app/app.env
    #     volumes:
    #       - snipesql-vol:/var/lib/mysql
    #     detach: yes
    #     exposed_ports:
    #       - 3306
    #     image: mysql:5.6
    #     published_ports:
    #       - "3306:3306"
    #     networks:
    #       - name: my-overlay-net
    #     state: started

    - name: Creating mysql container & joining overlay network using shell
      shell: docker run --name snipe-mysql --network my-overlay-net --env-file=/home/ubuntu/app/app.env --mount source=snipesql-vol,target=/var/lib/mysql -d -p 3306:3306 mysql:5.6

    - name: Check if container is running
      shell: docker ps
