---
- hosts: manager
  remote_user: ubuntu
  become: yes
  gather_facts: False

  pre_tasks:
    - name: 'install python'
      raw: 'sudo apt-get -y install python'

    - name: 'install pip'
      raw: 'sudo apt-get update && sudo apt-get install python-pip -y'

    - name: 'Install docker-py module'
      raw: 'sudo pip install docker-py'

  tasks:

    - name: "APT - Add Docker GPG key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "APT - Add Docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
        filename: docker

    - name: "APT - install misc packages"
      apt:
        name: ['aptitude', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        update_cache: yes

    - name: "APT - install 'docker-ce'"
      apt:
        name: "docker-ce"
        update_cache: yes

    - name: Swarm initialiasation
      docker_swarm:
        state: present
        advertise_addr: 192.168.10.100

    - name: Get docker swarm worker token
      shell: docker swarm join-token -q worker
      register: worker_token

    - name: Print out worker_token
      debug: msg="{{ worker_token.stdout }}"

    - name: Copy worker token to a YAML variable file 
      lineinfile:
        dest: ./token.yml
        regexp: "^WORKER_TOKEN: "
        line: "WORKER_TOKEN: {{ worker_token.stdout}}"

    # Does not work yet. Attachable feature to be added to docker_network module on Anssible 2.8
    # - name: Create Overlay network
    #   docker_network:
    #     name: my_overlay_net
    #     driver: overlay
    #     state: present
    #     attachable: true

    - name:  Creating a overlay network using shell command
      shell: docker network create --driver=overlay --attachable my-overlay-net
